name: Deploy TH test

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-name:
        required: true
        type: string
jobs:
  deploy-TH:
    runs-on: ubuntu-latest
    name: Deploy to TH
    env:
      SOME_CONFIG: "this is thailand config"
    if: startsWith(github.head_ref, 'TH-') || startsWith(github.head_ref, 'ALL-')
    steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      - name: Deploy Docker image
        run: |
          gcloud run deploy th-${{ inputs.environment }}-server --image ${{ inputs.image-name }} --region asia-southeast1 --platform managed \
              --set-env-vars=SOME_CONFIG="${{ env.SOME_CONFIG }}",SAME_SECRET="${{ secrets.SAME_SECRET }}",SOME_SECRET="${{ secrets.TH_SECRET }}" \
               --allow-unauthenticated